// ─────────────────────────────────────────────────────────────
//  Site-wide settings for SEO, social previews and analytics.
//  Values come from env vars (set in .env.local or the GitHub Actions workflow).
// ─────────────────────────────────────────────────────────────

/** Origin the site is served from, e.g. "https://adnangul.com" (no trailing slash). */
export const SITE_URL = (process.env.NEXT_PUBLIC_SITE_URL || "https://adnangul.com").replace(/\/$/, "").replace(/^http:\/\//, "https://");

/** GitHub Pages project path, e.g. "/personal-portfolio-" (empty for a root / user site). */
export const BASE_PATH = process.env.NEXT_PUBLIC_BASE_PATH || "";

/** Absolute URL for a page path, e.g. absoluteUrl("/blog/") → "https://…/personal-portfolio-/blog/". */
export const absoluteUrl = (path = "/") => `${SITE_URL}${BASE_PATH}${path.startsWith("/") ? path : `/${path}`}`;

/** Open Graph `images` entry for a page's og.png (generated by app/**\/og.png/route.tsx). */
export const ogImage = (pagePath: string, alt: string) => [
  { url: absoluteUrl(`${pagePath.replace(/\/$/, "")}/og.png`), width: 1200, height: 630, alt, type: "image/png" },
];

/** Google Analytics 4 measurement ID ("G-XXXXXXX"). Analytics stays off while empty. */
export const GA_ID = process.env.NEXT_PUBLIC_GA_ID || "";

/** Cloudflare Web Analytics beacon token (cookieless). Stays off while empty. */
export const CF_BEACON_TOKEN = process.env.NEXT_PUBLIC_CF_BEACON_TOKEN || "";

/** Google Search Console HTML-tag verification code (the `content` value only). */
export const GSC_VERIFICATION = process.env.NEXT_PUBLIC_GSC_VERIFICATION || "";

export const SEO_KEYWORDS = [
  "Senior Full Stack Developer",
  "React developer",
  "Next.js developer",
  "TypeScript",
  "Node.js",
  "NestJS",
  "Frontend performance",
  "System design",
  "Remote software engineer",
];
